In [1]:
import numpy as np

In [2]:
# 0부터 14까지 15개의 숫자를 (3,5) == [3][5] 차원으로 생성한다.
arr1 = np.arange(15).reshape(3, 5)
arr1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [3]:
# 데이터 차원의 확인
arr1.shape

(3, 5)

In [4]:
# 변수 타입의 확인
arr1.dtype

dtype('int32')

In [5]:
# zeros() 함수는 0으로 채워진 넘파이 배열을 생성하는 함수입니다. 1을 채워주는 역할을 하는 함수는 ones() 입니다.
arr3 = np.zeros((3,4))
arr3

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [8]:
arr4 = np.array([
    [1,2,3],
    [4,5,6]
], dtype = np.float64)

arr5 = np.array([
    [7,8,9],
    [10,11,12]
], dtype = np.float64)

# 사칙연산을 출력합니다.
print("arr4 + arr5 = ")
print(arr4 + arr5, "\n")
print("arr4 - arr5 = ")
print(arr4 - arr5, "\n")
print("arr4 * arr5 = ")
print(arr4 * arr5, "\n")
print("arr4 / arr5 = ")
print(arr4 / arr5, "\n")

arr4 + arr5 = 
[[ 8. 10. 12.]
 [14. 16. 18.]] 

arr4 - arr5 = 
[[-6. -6. -6.]
 [-6. -6. -6.]] 

arr4 * arr5 = 
[[ 7. 16. 27.]
 [40. 55. 72.]] 

arr4 / arr5 = 
[[0.14285714 0.25       0.33333333]
 [0.4        0.45454545 0.5       ]] 

